# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e514c6917d1bf4464016ebd074119fbc0b8f874d48afb44bbb8f422b26dd49edb1d10a79595700c3513ce19c1ea4b2bab93de248b5f533a83c898ca8b672479f

test:
  secret_key_base: 6a5b18b34015eee18e43e458d5d86ea2f6fabdedb1afca5babdd84575f6f94ecb9288f24faa862bb1c9109861bc4e9665be41bcecea0c0b139d4d43472d41d07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
